### ISSUE TITLE
Reproduce Waymo segmentation results.

### ISSUE THREAD

**Issue by synsin0** [PJLab-ADG/PCSeg#7]
Thanks for your great work. I try to reproduce mIoU=69.20 for cfgs/voxel/waymo/minkunet_mk34_cr16.yaml. I use 2x A6000 with the default training schedule, batch_size=1 epochs=12, my reproduced results have mIoU<30. May you share some training details for waymo dataset, about the training schedule and GPUs. Besides, I can reproduce results of minkowskinet on semantickitti dataset.

**Comment by BAI-Yeqi** [comment]
Please increase your per_gpu_batch_size. Ideally total_batch_size (n_gpu x per_gpu_batch_size) should be 32 (preferred) or 16.

**Comment by datouready** [comment]
@synsin0 Hello, I also encountered the same problem, n_gpu x per_gpu_batch_size=4*8=32， Finall, my reproduced results have mIoU<29.07，how did you solve this problem？

**Comment by datouready** [comment]
It is necessary to carefully check the generated *. npy files, preferably visualized files
